server:
  port: 5200

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/publicservice?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: none


huaxin:
  security:
    browser:
      loginPage: /signIn.html
      imageCode:
        urls: /authentication/form
      smsCode:
        urls: /authentication/mobile
    social:
          qq:
            app-id: todo
            app-secret: todo

